# User Actions
record_new_cycle: 1   # 0 -> False/1 -> True
day_of_cycle: 1
reset: 0              # 0 -> False/1 -> True

# Model Params
max_cycle_length: 99
default_cycle_length: 28
average_min: 21
average_max: 39
end_of_cycle_alert_days: 3
regular_cycle_range_min: 26
regular_cycle_range_max: 32
fertile_window_start: 8
fertile_window_end: 19
beep_alert_on: 8
beep_alert_off: 20
average_window: 3

# Save Data
save_path: C:\flutter_dev\2024-IMMI\web_app\prediction_algorithm
save_file_name: cycle_data.txt